SRC_NAME = EasyTier
THISDIR = $(shell pwd)

all:

extract_test:

config_test:

clean:

romfs:
	$(ROMFSINST) $(THISDIR)/easytier-core    /etc/storage/bin/easytier-core
	$(ROMFSINST) $(THISDIR)/easytier-cli     /etc/storage/bin/easytier-cli
	$(ROMFSINST) $(THISDIR)/easytier.sh      /usr/bin/easytier.sh